### ISSUE TITLE
Add https://rstudio.github.io/r-manuals/ as repo's URL

### ISSUE THREAD

**Issue by jennybc** [rstudio/r-manuals#2]
This will make it even easier to go back and forth between the source and rendered product.

<https://rstudio.github.io/r-manuals/>

**Comment by cderv** [comment]
I have added the url to the repo home page : https://github.com/rstudio/r-manuals

is that what you meant by "repo's URL" ? 

Or do you have another place in mind ?

**Comment by jennybc** [comment]
Yeah that's exactly what I meant. Thanks!
