### ISSUE TITLE
Fix GH builds 

### ISSUE THREAD

**Issue by cderv** [rstudio/r-manuals#5]
Build is failling since some months now. Need to fix to get new manuals version

**Comment by andrie** [comment]
I fixed this (temporarily) using a fixed version of `pandoc-2.19`, rather than the pandoc built into Quarto

**Comment by cderv** [comment]
Thanks a lot ! 

Did you pinpoint what the issue was ? It seems odd that we need a newer pandoc than the one included with Quarto 🤔
I plan to have a look end of august at this.
